source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def common_pods
  pod 'ITLinkRouter', :path => '../'
end

def rambler_pods
    pod 'Typhoon'
    pod 'RamblerTyphoonUtils'
    pod 'ViperMcFlurry'
end


target 'ITLinkRouter_Example', :exclusive => true do
    common_pods
    rambler_pods
    pod 'SpaceCommander', :git => 'https://github.com/alesanro/spacecommander.git'
end

target 'ITLinkRouter_Storyboard_Example', :exclusive => true do
    common_pods
    rambler_pods
end

target 'ITLinkRouter_Tests', :exclusive => true do
    common_pods

    pod 'Specta'
    pod 'Expecta'
    pod 'OCMock'
end
