source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ITLinkRouter_Example', :exclusive => true do
  pod 'ITLinkRouter', :path => '../'

  pod 'ViperMcFlurry'
end

target 'ITLinkRouter_Tests', :exclusive => true do
  pod 'ITLinkRouter', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
